---
- name: Install Apache2
  apt:
      name: "apache2"
      state: latest
      update_cache: yes

- name: Install PHP
  apt:
    name:
      - "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - php
    - libapache2-mod-php
    - php7.3-fpm
  notify:
      - restart apache2

- name: "Create virtualhost for frontend-domains"
  template:
      src: apache-hostfile.j2
      dest: "/etc/apache2/sites-available/{{ item }}.conf"
      owner: root
      group: root
      mode: '0644'
      force: no # certbot will change the files for https setup
  vars:
    frontendSourceDirectory: "{{ frontend[0] }}"
  with_items: "{{ frontend }}"
  notify:
      - restart apache2

- name: "Create virtualhost for backend-domains"
  template:
      src: api.apache-hostfile.j2
      dest: "/etc/apache2/sites-available/{{ item }}.conf"
      owner: root
      group: root
      mode: '0644'
      force: no # certbot will change the files for https setup
  vars:
    backendSourceDirectory: "{{ backend[0] }}"
  with_items: "{{ backend }}"
  notify:
      - restart apache2

- name: "Create /var/www directory for backend"
  file:
      path: "/var/www/{{ backend[0] }}"
      state: directory
      owner: www-data
      group: www-data
      mode: ug=rwxs,o=rx

- name: "Create /var/www directory for frontend"
  file:
      path: "/var/www/{{ frontend[0] }}"
      state: directory
      owner: www-data
      group: www-data
      mode: ug=rwxs,o=rx

- name: "Enable apache2 site {{ item }}"
  command: a2ensite {{ item }}
  args:
      creates: /etc/apache2/sites-enabled/{{ item }}.conf
  with_items:
    - "{{ frontend }}"
    - "{{ backend }}"
  notify:
      - restart apache2

- name: Enable apache module {{ item }}
  apache2_module: name={{ item }} state=present
  with_items:
      - http2
      - rewrite
      - ssl
      - headers
      - socache_shmcb
      - expires
      - proxy
  notify:
      - restart apache2

- name: Add intermediate-ssl config
  copy:
      src: intermediate-ssl.conf
      dest: /etc/apache2/conf-available/intermediate-ssl.conf
      owner: root
      group: root
      mode: '0644'
- name: Enable intermediate-ssl config
  command: a2enconf intermediate-ssl
  args:
      creates: /etc/apache2/conf-enabled/intermediate-ssl.conf
  notify:
      - restart apache2

- name: Enable fpm conf
  command: a2enconf "{{ item }}"
  with_items:
    - php7.3-fpm
  notify:
    - restart apache2

- name: Install certbot
  apt:
      name: "certbot"
      state: latest
      update_cache: yes
- name: Install certbot apache plugin
  apt:
      name: "python-certbot-apache"
      state: latest
      update_cache: yes

# - name: "Certbot run for {{ item }}"
#   command: certbot run -n --apache --redirect --hsts --agree-tos --email "christoph.h@premium-kollektiv.de" -d {{ item }}
#   args:
#       creates: /etc/apache2/sites-available/{{ item }}-le-ssl.conf
#   with_items: "{{ domains }}"
#   notify:
#       - restart apache2
